events {
    worker_connections 1024;
}

http {
    client_max_body_size 10M;

    upstream backend {
        server backend:8000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
            add_header Access-Control-Allow-Headers "Content-Type";
        }

        location /health {
            proxy_pass http://backend;
        }
    }
}
